driver:
  name: vagrant
  require_chef_omnibus: true

chef_versions:
- 11
- 12

platforms:
  - name: gdp-centos-7.1
    driver:
      box: centos-71
      box_url: https://deploy.gmti.gbahn.net/Images/centos7/vagrant/centos71-cloud-1.0.0.box
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[supervisor::default]
  - name: in_systemd
    run_list:
    - recipe[supervisor::in_systemd]
